---
provisioner: chef_zero
driver:
  name: vagrant
  require_chef_omnibus: true   # :latest
#  http_proxy: http://33.33.33.9:8123
#  https_proxy: https://33.33.33.9:8123
  customize:
    memory: 1024
#  network:
#  - ["private_network", {ip: "33.33.33.7"}]
#  synced_folders:
#  - ["/home/local", "/home/vm"]

platforms:
- name: ubuntu-12.04
#- name: centos-6.4

suites:
- name: default
#  encrypted_data_bag_secret_key_path: "~/.chef/encrypted_data_bag_secret"
  run_list:
  - recipe[roadtalk::default]
  attributes:
    postgresql:
      password: 
        postgres: "password1"
